<html>
	<head>
	</head>
	<body>
		<script>
			_anchor = opener.window.document.querySelector('#google-accessor');
			_interval = setInterval(function() {
				let _value = _anchor.value;
				if(_value) {
					clearInterval(_interval);
					document.body.textContent = _value;
					window.close();
				} else if(_anchor) {
					_anchor.value = `<?=$access ?>`;
				}
			}, 100);
		</script>
	</body>
</html>