<?php

/**
 * Aditem
 * 
 * @autogenerated by Phalcon Developer Tools
 * @date 2019-06-12, 20:45:46
 */
class Aditem extends \Phalcon\Mvc\Model
{

    /**
     *
     * @var integer
     * @Primary
     * @Identity
     * @Column(column="id", type="integer", nullable=true)
     */
    protected $id;

    /**
     *
     * @var string
     * @Column(column="service", type="string", nullable=false)
     */
    protected $service;

    /**
     *
     * @var string
     * @Column(column="account_id", type="string", nullable=false)
     */
    protected $account_id;

    /**
     *
     * @var string
     * @Column(column="campaign_id", type="string", nullable=false)
     */
    protected $campaign_id;

    /**
     *
     * @var string
     * @Column(column="adgroup_id", type="string", nullable=false)
     */
    protected $adgroup_id;

    /**
     *
     * @var string
     * @Column(column="item_id", type="string", nullable=false)
     */
    protected $item_id;

    /**
     *
     * @var string
     * @Column(column="_access", type="string", nullable=true)
     */
    protected $_access;

    /**
     *
     * @var string
     * @Column(column="_account", type="string", nullable=true)
     */
    protected $_account;

    /**
     *
     * @var string
     * @Column(column="_campaign", type="string", nullable=true)
     */
    protected $_campaign;

    /**
     *
     * @var string
     * @Column(column="_adgroup", type="string", nullable=true)
     */
    protected $_adgroup;

    /**
     *
     * @var string
     * @Column(column="_iteminfo", type="string", nullable=true)
     */
    protected $_iteminfo;

    /**
     *
     * @var string
     * @Column(column="_errors", type="string", nullable=true)
     */
    protected $_errors;

    /**
     *
     * @var integer
     * @Column(column="status", type="integer", nullable=false)
     */
    protected $status;

    /**
     *
     * @var string
     * @Column(column="created_at", type="string", nullable=true)
     */
    protected $created_at;

    /**
     *
     * @var string
     * @Column(column="updated_at", type="string", nullable=true)
     */
    protected $updated_at;

    /**
     *
     * @var string
     * @Column(column="visited_at", type="string", nullable=true)
     */
    protected $visited_at;

    /**
     *
     * @var string
     * @Column(column="deleted_at", type="string", nullable=true)
     */
    protected $deleted_at;

    /**
     * Method to set the value of field id
     *
     * @param integer $id
     * @return $this
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Method to set the value of field service
     *
     * @param string $service
     * @return $this
     */
    public function setService($service)
    {
        $this->service = $service;

        return $this;
    }

    /**
     * Method to set the value of field account_id
     *
     * @param string $account_id
     * @return $this
     */
    public function setAccountId($account_id)
    {
        $this->account_id = $account_id;

        return $this;
    }

    /**
     * Method to set the value of field campaign_id
     *
     * @param string $campaign_id
     * @return $this
     */
    public function setCampaignId($campaign_id)
    {
        $this->campaign_id = $campaign_id;

        return $this;
    }

    /**
     * Method to set the value of field adgroup_id
     *
     * @param string $adgroup_id
     * @return $this
     */
    public function setAdgroupId($adgroup_id)
    {
        $this->adgroup_id = $adgroup_id;

        return $this;
    }

    /**
     * Method to set the value of field item_id
     *
     * @param string $item_id
     * @return $this
     */
    public function setItemId($item_id)
    {
        $this->item_id = $item_id;

        return $this;
    }

    /**
     * Method to set the value of field _access
     *
     * @param string $_access
     * @return $this
     */
    public function setAccess($_access)
    {
        $this->_access = $_access;

        return $this;
    }

    /**
     * Method to set the value of field _account
     *
     * @param string $_account
     * @return $this
     */
    public function setAccount($_account)
    {
        $this->_account = $_account;

        return $this;
    }

    /**
     * Method to set the value of field _campaign
     *
     * @param string $_campaign
     * @return $this
     */
    public function setCampaign($_campaign)
    {
        $this->_campaign = $_campaign;

        return $this;
    }

    /**
     * Method to set the value of field _adgroup
     *
     * @param string $_adgroup
     * @return $this
     */
    public function setAdgroup($_adgroup)
    {
        $this->_adgroup = $_adgroup;

        return $this;
    }

    /**
     * Method to set the value of field _iteminfo
     *
     * @param string $_iteminfo
     * @return $this
     */
    public function setIteminfo($_iteminfo)
    {
        $this->_iteminfo = $_iteminfo;

        return $this;
    }

    /**
     * Method to set the value of field _errors
     *
     * @param string $_errors
     * @return $this
     */
    public function setErrors($_errors)
    {
        $this->_errors = $_errors;

        return $this;
    }

    /**
     * Method to set the value of field status
     *
     * @param integer $status
     * @return $this
     */
    public function setStatus($status)
    {
        $this->status = $status;

        return $this;
    }

    /**
     * Method to set the value of field created_at
     *
     * @param string $created_at
     * @return $this
     */
    public function setCreatedAt($created_at)
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * Method to set the value of field updated_at
     *
     * @param string $updated_at
     * @return $this
     */
    public function setUpdatedAt($updated_at)
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * Method to set the value of field visited_at
     *
     * @param string $visited_at
     * @return $this
     */
    public function setVisitedAt($visited_at)
    {
        $this->visited_at = $visited_at;

        return $this;
    }

    /**
     * Method to set the value of field deleted_at
     *
     * @param string $deleted_at
     * @return $this
     */
    public function setDeletedAt($deleted_at)
    {
        $this->deleted_at = $deleted_at;

        return $this;
    }

    /**
     * Returns the value of field id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Returns the value of field service
     *
     * @return string
     */
    public function getService()
    {
        return $this->service;
    }

    /**
     * Returns the value of field account_id
     *
     * @return string
     */
    public function getAccountId()
    {
        return $this->account_id;
    }

    /**
     * Returns the value of field campaign_id
     *
     * @return string
     */
    public function getCampaignId()
    {
        return $this->campaign_id;
    }

    /**
     * Returns the value of field adgroup_id
     *
     * @return string
     */
    public function getAdgroupId()
    {
        return $this->adgroup_id;
    }

    /**
     * Returns the value of field item_id
     *
     * @return string
     */
    public function getItemId()
    {
        return $this->item_id;
    }

    /**
     * Returns the value of field _access
     *
     * @return string
     */
    public function getAccess()
    {
        return $this->_access;
    }

    /**
     * Returns the value of field _account
     *
     * @return string
     */
    public function getAccount()
    {
        return $this->_account;
    }

    /**
     * Returns the value of field _campaign
     *
     * @return string
     */
    public function getCampaign()
    {
        return $this->_campaign;
    }

    /**
     * Returns the value of field _adgroup
     *
     * @return string
     */
    public function getAdgroup()
    {
        return $this->_adgroup;
    }

    /**
     * Returns the value of field _iteminfo
     *
     * @return string
     */
    public function getIteminfo()
    {
        return $this->_iteminfo;
    }

    /**
     * Returns the value of field _errors
     *
     * @return string
     */
    public function getErrors()
    {
        return $this->_errors;
    }

    /**
     * Returns the value of field status
     *
     * @return integer
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Returns the value of field created_at
     *
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Returns the value of field updated_at
     *
     * @return string
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * Returns the value of field visited_at
     *
     * @return string
     */
    public function getVisitedAt()
    {
        return $this->visited_at;
    }

    /**
     * Returns the value of field deleted_at
     *
     * @return string
     */
    public function getDeletedAt()
    {
        return $this->deleted_at;
    }

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSource("items");
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'items';
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return Aditem[]|Aditem|\Phalcon\Mvc\Model\ResultSetInterface
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return Aditem|\Phalcon\Mvc\Model\ResultInterface
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

}
